name: Feature request
description: Suggest an idea for this project
title: "[Feature]: An explicit title"
labels: enhancement
assignees: l3alr0g
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: describe
    attributes:
      label: Describe your idea
      description: Be precise and explicit, provide screenshots if necessary
      placeholder: I would like the installer to be more user-friendly
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/l3alr0g/Slashboard-pulsar/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow Pulsar's Code of Conduct
          required: true
